name: Lint, Test, Build

on:
  push:
    tags-ignore:
      - "v*"
    branches:
      - "**"
  pull_request:

jobs:
  lintTestBuild:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libpcsclite-dev
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "latest"
          args: --timeout=5m
      - name: Test, Build
        id: testAndBuild
        run: V=1 make ci
