name: Lint, Test, Build

on:
  push:
    tags-ignore:
    - 'v*'
    branches:
    - "**"
  pull_request:

jobs:
  lintTestBuild:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      -
        name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: 'v1.46.2'
          args: --timeout=30m
      -
        name: Test, Build
        id: lintTestBuild
        run: V=1 make ci
